### ISSUE TITLE
Coordinates regenerated despite being provided

### ISSUE THREAD

**Issue by baoilleach** [kienerj/pycdxml#26] opened 2022-12-16 18:29 UTC
For the structure CHEMBL488297, instead of just depicting the structure as provided, conversion from MOL to CDXML causes the coordinates to regenerate. It also inverts the stereo.
[CHEMBL4889297.mol.txt](https://github.com/kienerj/pycdxml/files/10248161/CHEMBL4889297.mol.txt)
[CHEMBL4889297.cdxml.txt](https://github.com/kienerj/pycdxml/files/10248188/CHEMBL4889297.cdxml.txt)

The only weird thing about this file (and another I looked at) is that the Z coordinates are all -0.0000 instead of just 0.0000. Does RDKit fail to recognise this as a 2D conformer? Not sure what's with the stereo inversion - something to do with the difference in coordinates between MOL file and CDXML?

MOL file:
![image](https://user-images.githubusercontent.com/45337/208164510-c38d2f36-a68a-48ec-b789-0b8d95075495.png)
CDXML:
![image](https://user-images.githubusercontent.com/45337/208164569-80c7555c-5d66-48e4-9aaf-0bca8c5f317c.png)

**Comment by kienerj** [comment] 2022-12-18 09:27
I will look into it. likley it's caused by pycdxml code as I'm checking if there are 3D coordinates and if yes generate 2D. Possibly that the -0.0 somehow triggers that 2D coordinates generation. (Possibly floating point accuracy issue and it's not 0?)

**Comment by kienerj** [comment] 2022-12-19 07:31
fixed with eade22ec0355f055a597e85d8cb4e5a2464a22c8

Indeed as expected determining if a 3D structure (recompute 2D) or a 2D structure (generate 2d) is present was wrong and fails in case the maximum point (atom) is exactly at 0 0 0 and all others are negative coordinates.

Weber it doesn't explain why 2D coordinate regeneration using coordgen:

```
 rdCoordGen.AddCoords(mol)
 mol.UpdatePropertyCache()
```

changes stereo chemistry. So there might be a bug in that code as well for this specific molecule?

Additional which bond is wedged still changes compared to the molfile as I'm using rdkits wedging so this molecule looks like below in cdxml:

![image](https://user-images.githubusercontent.com/1567309/208371151-3d6fd31a-6664-4767-bcd5-60182b877d0b.png)

**Closed by kienerj** 2022-12-19 07:31 UTC
