### ISSUE TITLE
Conversion from MOL to CDXML fails for CHEMBL69710

### ISSUE THREAD

**Issue by baoilleach** [kienerj/pycdxml#24] opened 2022-11-13 20:40 UTC
The CHEMBL entry for LiCl triggers an error:
[CHEMBL69710.mol.txt](https://github.com/kienerj/pycdxml/files/9998148/CHEMBL69710.mol.txt)
```
  doc = cdxml_converter.mol_to_document(mol)
  File "...\pycdxml\pycdxml\cdxml_converter\rdkit_chemdraw.py", line 97, in mol_to_document
    p = str(atom_coords[idx][0]) + " " + str(atom_coords[idx][1])
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by kienerj** [comment] 2022-11-14 05:42
Duplicate of #19

**Closed by kienerj** 2022-11-14 05:42 UTC
